casLogoutUrl: https://localhost:10100/cas/logout

security:
  basic:
    enabled: false
  ignored: /, /**/favicon.ico

cas:
  server-url-prefix: https://${cas_server:localhost}:10100/cas
  server-login-url: https://localhost:10100/cas/login
  client-host-url: https://localhost:12000

spring:
  thymeleaf:
    # For dev
    cache: false

server:
  port: 12000
  ssl:
    enabled: true
    key-store: classpath:keystore/localhost.jks
    key-store-password: changeit

logging.level:
    org.jasig.cas: INFO